name: Integration Tests - Gemini

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  integration-tests-gemini:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpoppler-cpp-dev tesseract-ocr
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio pytest-cov
        pip install -r requirements.txt
        pip install -e .
    
    - name: Start ChromaDB
      run: |
        docker run -d -p 8000:8000 --name chromadb chromadb/chroma:0.4.15
        sleep 10
    
    - name: Run integration tests with Gemini
      env:
        LLM_PROVIDER: gemini
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        CHROMA_DB_HOST: localhost
        CHROMA_DB_PORT: 8000
        CHROMA_DB_USE_REMOTE: true
        LOG_LEVEL: INFO
        LOG_FORMAT: text
      run: |
        pytest tests/integration/ -v --cov=testteller --cov-report=xml -m "integration and not slow" -k "gemini or (not (openai or claude or llama))"
    
    - name: Run CLI tests with Gemini
      env:
        LLM_PROVIDER: gemini
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        CHROMA_DB_HOST: localhost
        CHROMA_DB_PORT: 8000
        CHROMA_DB_USE_REMOTE: true
        LOG_LEVEL: INFO
        LOG_FORMAT: text
      run: |
        pytest tests/cli/ -v -m "cli and not slow"
    
    - name: Stop ChromaDB
      if: always()
      run: |
        docker stop chromadb || true
        docker rm chromadb || true
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: integration-gemini
        name: integration-tests-gemini
        fail_ci_if_error: false 